//! Reading the two config files and layering them into one [`Config`].
//!
//! The base file is what Nix (or a person) wrote; the overrides file is what
//! the settings UI writes. Tables merge key by key, and any other value in the
//! overrides replaces the base value whole (so a list is replaced, not
//! appended to).

use std::path::Path;

use toml::{Table, Value};

use crate::schema::Config;

/// The outcome of loading: the config plus anything worth telling the person.
#[derive(Debug, Clone, PartialEq)]
pub struct Loaded {
    pub config: Config,
    /// Unknown keys and semantic problems. The config is still usable.
    pub warnings: Vec<String>,
}

/// Read a TOML file into a table. A missing file is an empty table.
pub fn read_table(path: &Path) -> Result<Table, String> {
    match std::fs::read_to_string(path) {
        Ok(text) => parse_table(&text).map_err(|e| format!("{}: {e}", path.display())),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Table::new()),
        Err(e) => Err(format!("{}: {e}", path.display())),
    }
}

pub fn parse_table(text: &str) -> Result<Table, String> {
    text.parse::<Table>().map_err(|e| e.message().to_owned())
}

/// Merge `top` onto `base`: tables recursively, everything else replaced.
pub fn merge(base: &mut Table, top: Table) {
    for (key, value) in top {
        match (base.get_mut(&key), value) {
            (Some(Value::Table(below)), Value::Table(above)) => merge(below, above),
            (_, value) => {
                base.insert(key, value);
            }
        }
    }
}

/// Turn a merged table into a typed config. `Err` means the values do not fit
/// the schema (a string where a number goes, an unknown enum value, …).
pub fn to_config(table: Table) -> Result<Loaded, String> {
    let mut warnings = Vec::new();
    let config: Config = serde_ignored::deserialize(Value::Table(table), |path| {
        warnings.push(format!("unknown key {}", dotted(&path)));
    })
    .map_err(|e| e.message().to_owned())?;
    warnings.extend(config.check());
    Ok(Loaded { config, warnings })
}

/// Render a serde_ignored path as `a.b.c`.
fn dotted(path: &serde_ignored::Path<'_>) -> String {
    path.to_string().trim_start_matches('?').to_owned()
}

/// Split `ui.cornerRadius` into its segments. Empty segments are rejected.
pub fn key_path(key: &str) -> Result<Vec<&str>, String> {
    let parts: Vec<&str> = key.split('.').collect();
    if parts.iter().any(|p| p.is_empty()) {
        return Err(format!("invalid key {key:?}"));
    }
    Ok(parts)
}

/// Look up a dotted key in a table.
pub fn lookup<'a>(table: &'a Table, key: &str) -> Option<&'a Value> {
    let parts = key_path(key).ok()?;
    let (last, parents) = parts.split_last()?;
    let mut current = table;
    for part in parents {
        current = current.get(*part)?.as_table()?;
    }
    current.get(*last)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::Density;

    fn table(text: &str) -> Table {
        parse_table(text).unwrap()
    }

    #[test]
    fn overrides_win_and_tables_merge() {
        let mut base = table(
            r#"
            [ui]
            density = "compact"
            cornerRadius = 4
            [adblock]
            lists = ["easylist", "easyprivacy"]
            "#,
        );
        merge(
            &mut base,
            table(
                r#"
                [ui]
                cornerRadius = 12
                [adblock]
                lists = ["easylist"]
                "#,
            ),
        );
        let config = to_config(base).unwrap().config;
        assert_eq!(config.ui.density, Density::Compact);
        assert_eq!(config.ui.corner_radius, 12);
        assert_eq!(config.adblock.lists, vec!["easylist".to_owned()]);
    }

    #[test]
    fn unknown_keys_are_warnings() {
        let loaded = to_config(table(
            "[ui]\ncornerRadius = 3\nwobble = true\n[future]\nx = 1",
        ))
        .unwrap();
        assert_eq!(loaded.config.ui.corner_radius, 3);
        assert_eq!(
            loaded.warnings,
            vec!["unknown key future", "unknown key ui.wobble"]
        );
    }

    #[test]
    fn home_manager_output_loads_cleanly() {
        // Generated by nix/hm-module.nix; the `hm-module` flake check keeps it current.
        let text = include_str!("../tests/fixtures/hm-module.toml");
        let loaded = to_config(parse_table(text).unwrap()).unwrap();
        assert!(loaded.warnings.is_empty(), "{:?}", loaded.warnings);
        assert_eq!(loaded.config.ui.animations.speed, 1.5);
        assert!(!loaded.config.general.restore_session);
        assert_eq!(loaded.config.bangs.len(), 2);
    }

    #[test]
    fn wrong_types_are_errors() {
        let err = to_config(table("[ui]\ncornerRadius = \"big\"")).unwrap_err();
        assert!(
            err.contains("cornerRadius") || err.contains("invalid type"),
            "{err}"
        );
        assert!(to_config(table("[ui]\ndensity = \"huge\"")).is_err());
    }

    #[test]
    fn missing_file_is_empty() {
        let dir = tempfile::tempdir().unwrap();
        assert!(
            read_table(&dir.path().join("nope.toml"))
                .unwrap()
                .is_empty()
        );
    }

    #[test]
    fn parse_errors_name_the_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(&path, "[ui\n").unwrap();
        assert!(read_table(&path).unwrap_err().contains("config.toml"));
    }

    #[test]
    fn lookup_follows_dotted_keys() {
        let t = table("[ui.animations]\nspeed = 2.0");
        assert_eq!(lookup(&t, "ui.animations.speed"), Some(&Value::Float(2.0)));
        assert_eq!(lookup(&t, "ui.nope"), None);
        assert_eq!(lookup(&t, "ui..x"), None);
    }
}
